### ISSUE TITLE
missing bracer.conf

### ISSUE THREAD

**Issue by ibseq** [Teichlab/bracer#14]
Hello, 
i have created a conda env and istalled bracer, but when i ran the test run i get:
"Couldn't find config file: /home/ib/anaconda3/envs/BRACER/lib/python3.6/site-packages/bracer.conf"

which effectively is not in that directory

any advice?
thanks
ib

**Comment by ibseq** [comment]
HI there
I just had chance now to use bracer with my now results. 

I tried to run the test as well but I’m stuck with the original issue, config file not found, called with -c of course

any advice?

thanks!
irene

**Comment by idalind** [comment]
Hi @ibseq ,
This seems strange. I'm not sure how much I can help you without more information, perhaps some screenshots? Where is your config file located? Are you specifying another config file location, but bracer looks for it at /home/ib/anaconda3/envs/BRACER/lib/python3.6/site-packages/bracer.conf ?

**Comment by ibseq** [comment]
HI
it says there is no config file in the path indicated. 

what i have tried was to copy it from the website and created and saved it where is supposed to be but it didn’t work


irene

**Comment by idalind** [comment]
Hi again, could you please provide me some screenshots of the commands you are using and the resulting error? Without such information it is hard for me to give any advice.

**Comment by ibseq** [comment]
Hi Ida, here it is: I’m running it very simple

bracer assemble 1R1.fastq.gz 1R2.fastq.gz 
Config file not found at ~/.bracerrc. Using default bracer.conf in repo...
Please specify the path to where you originally installed BraCeR in the config file.
Traceback (most recent call last):
  File "/home/ibassano/anaconda3/envs/BRACER/bin/bracer", line 11, in <module>
    load_entry_point('bracer==0.1', 'console_scripts', 'bracer')()
  File "/home/ibassano/anaconda3/envs/BRACER/lib/python3.6/site-packages/bracerlib/launcher.py", line 43, in launch
    Task().run()
  File "/home/ibassano/anaconda3/envs/BRACER/lib/python3.6/site-packages/bracerlib/tasks.py", line 290, in __init__
    root=resource_dir)
  File "/home/ibassano/anaconda3/envs/BRACER/lib/python3.6/site-packages/bracerlib/tasks.py", line 177, in get_species_root
    assert os.path.isdir(resources_root), "Species not found in resources"
AssertionError: Species not found in resources

BW
Irene

**Comment by ibseq** [comment]
and config file is where is supposed to be: just see top list


/home/ibassano/anaconda3/envs/BRACER/lib/python3.6/site-packages$ ll
4096 May 14  2018 Bio
4096 May 14  2018 biopython-1.71-py3.6.egg-info
4096 May 14  2018 BioSQL
4096 May 14  2018 bracer-0.1-py3.6.egg-info
 916 Dec 11 14:59 bracer.conf
4096 May 14  2018 bracerlib
4096 May 14  2018 certify

**Comment by ibseq** [comment]
latest error with same command. I adjusted the cons file to just indicate the path
Traceback (most recent call last):
  File "/home/ibassano/anaconda3/envs/BRACER/bin/bracer", line 11, in <module>
    load_entry_point('bracer==0.1', 'console_scripts', 'bracer')()
  File "/home/ibassano/anaconda3/envs/BRACER/lib/python3.6/site-packages/bracerlib/launcher.py", line 43, in launch
    Task().run()
  File "/home/ibassano/anaconda3/envs/BRACER/lib/python3.6/site-packages/bracerlib/tasks.py", line 290, in __init__
    root=resource_dir)
  File "/home/ibassano/anaconda3/envs/BRACER/lib/python3.6/site-packages/bracerlib/tasks.py", line 177, in get_species_root
    assert os.path.isdir(resources_root), "Species not found in resources"
AssertionError: Species not found in resources

**Comment by xf78** [comment]
I had the same problem that “AssertionError: Species not found in resources”，while reading the detailed documentation:https://github.com/Teichlab/bracer/,i found that i set "bracer_path" parameter wrong,"bracer_path" should be the dirpath of bracer executable file ,another reason maybe kallisto_transcriptomes must be fa file.
