### ISSUE TITLE
linalgerror

### ISSUE THREAD

**Issue by michael-swift** [Teichlab/bracer#26]
Hi bracer team, 

thanks for writing this software. I am trying to use the program but it is failing the tests. I downloaded bracer today 
`git clone https://github.com/Teichlab/bracer.git` 
Then I created a new conda environment for bracer. I installed numpy and biopython in that environment. then installed the other modules using pip3 and the requirements.txt file. 

When I run the test: ./bracer test -c bracer.conf

I get this error: 

PROGRESS> 14:07:16 |Loading files       | 0.0 min PROGRESS> 14:07:16 |Done                | 0.0 min

PROGRESS> 14:07:16 |                    |   0% (0) 0.0 min^MPROGRESS> 14:07:16 |##########          |  50% (1) 0.0 min PROGRESS> 14:07:16 |####################| 100% (2) 0.0 min

OUTPUT> cell1_BCR_L_db-pass.tab
  PASS> 2
  FAIL> 0
   END> MakeDb

       START> DefineClones
        FILE> changeo_input_H.tab
   SEQ_FIELD> JUNCTION
     V_FIELD> V_CALL
     J_FIELD> J_CALL
 MAX_MISSING> 0

/home/users/mswift2/.local/lib/python3.6/site-packages/scipy/stats/stats.py:1713: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return np.add.reduce(sorted[indexer] * weights, axis=axis) / sumval
Traceback (most recent call last):
  File "./bracer", line 21, in <module>
    launch()
  File "/oak/stanford/groups/quake/mswift/resources/bracer/bracerlib/launcher.py", line 43, in launch
    Task().run()
  File "/oak/stanford/groups/quake/mswift/resources/bracer/bracerlib/tasks.py", line 1951, in run
    infer_lineage=self.infer_lineage, species='Hsap').run()
  File "/oak/stanford/groups/quake/mswift/resources/bracer/bracerlib/tasks.py", line 867, in run
    self.plot_length_distributions(self.loci, length_filename_root, cells)
  File "/oak/stanford/groups/quake/mswift/resources/bracer/bracerlib/tasks.py", line 1194, in plot_length_distributions
    sns.distplot(lns)
  File "/oak/stanford/groups/quake/mswift/resources/miniconda3/lib/python3.6/site-packages/seaborn/distributions.py", line 231, in distplot
    kdeplot(a, vertical=vertical, ax=ax, color=kde_color, **kde_kws)
  File "/oak/stanford/groups/quake/mswift/resources/miniconda3/lib/python3.6/site-packages/seaborn/distributions.py", line 691, in kdeplot
    cumulative=cumulative, **kwargs)
  File "/oak/stanford/groups/quake/mswift/resources/miniconda3/lib/python3.6/site-packages/seaborn/distributions.py", line 294, in _univariate_kdeplot
    x, y = _scipy_univariate_kde(data, bw, gridsize, cut, clip)
  File "/oak/stanford/groups/quake/mswift/resources/miniconda3/lib/python3.6/site-packages/seaborn/distributions.py", line 366, in _scipy_univariate_kde
    kde = stats.gaussian_kde(data, bw_method=bw)
  File "/home/users/mswift2/.local/lib/python3.6/site-packages/scipy/stats/kde.py", line 172, in __init__
    self.set_bandwidth(bw_method=bw_method)
  File "/home/users/mswift2/.local/lib/python3.6/site-packages/scipy/stats/kde.py", line 499, in set_bandwidth
    self._compute_covariance()
  File "/home/users/mswift2/.local/lib/python3.6/site-packages/scipy/stats/kde.py", line 510, in _compute_covariance
    self._data_inv_cov = linalg.inv(self._data_covariance)
  File "/home/users/mswift2/.local/lib/python3.6/site-packages/scipy/linalg/basic.py", line 975, in inv
    raise LinAlgError("singular matrix")
numpy.linalg.linalg.LinAlgError: singular matrix

seemed like a non-critical portion of the program so I commented the lines out: 
`for l in loci:
            q = quartiles[l]
            lns = lengths[l]
            print(lns)
            if len(lns) > 1:
                print("length >1")
                pass
                #plt.figure()                                                                                                                                                 
                #plt.axvline(q[0], linestyle="--", color='k')                                                                                                                 
                #plt.axvline(q[1], linestyle="--", color='k')                                                                                                                 
                #sns.distplot(lns)                                                                                                                                            
sns.            #sns.despine()                                                                                                                                                
                #plt.xlabel("BCR_{} reconstructed length (bp)".format(l))                                                                                                     
                #plt.ylabel("Density")                                                                                                                                        
                #plt.savefig("{}_{}.pdf".format(length_filename_root, l))                                                                                                     
            if len(lns) > 0:
                with open("{}_{}.txt".format(length_filename_root,l), 'w') as f:
                    for l in sorted(lns):
                        f.write("{}\n".format(l))`

The program then unceremoniously ends right after the MakeDB step. I when I look at the expected results compared to the test results, the IGHG sequence is missing from the output the test generates. 

Hopefully you can help! 

Thanks,
Michael

**Comment by michael-swift** [comment]
Hi Ida, I've pulled the most recent version of Bracer using this Conda environment 
[bracer_working.txt](https://github.com/Teichlab/bracer/files/2818562/bracer_working.txt) and the tests seem to work. Thanks!
