### ISSUE TITLE
Cannot run the docker image

### ISSUE THREAD

**Issue by NicolasHipp** [Teichlab/bracer#30]
hi everyone,
First , I wish you a Happy New year !!!
I would like to test Bracer with the Docker Image, but I'm stuck at the start of the tutorial. 

`pip3 install -r /bracer/requirements.txt
`
```
$ /bracer/bracer/test
-sh: 174: /bracer/bracer/test: not found
$ /bracer/bracer test
Traceback (most recent call last):
  File "/bracer/bracer", line 17, in <module>
    from bracerlib.launcher import launch
  File "/bracer/bracerlib/launcher.py", line 2, in <module>
    import matplotlib as mpl
ImportError: No module named matplotlib
```

I add the path of matplolib,and the bracer path in my PATH, but nothing change
`/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/nhipp/.local/lib/python3.5/site-packages/:/home/nhipp/.local/lib/python3.5/site-packages/matplotlib:/bracer`

Maybe my brain is still in holliday but I cannot solve the problem.
Does-anybody have an idea !

EDIT: I used a ssh interactive Docker job submission, that why the command is not complete (in regard of the tutorial)
nicolas

**Comment by NicolasHipp** [comment]
Find it, It come from my docker environment, sorry
