### ISSUE TITLE
summarise command on test_data fails

### ISSUE THREAD

**Issue by UtaHar** [Teichlab/bracer#38]
Dear BraCeR team,

I built a bracer singularity image from the docker to run it on a HPC. However, the summarise command on the test_data fails. Any idea from the error message, what happend?

Singularity bracer.simg:~> bracer summarise /data/results

     START> DefineClones
   DB_FILE> changeo_input_H.tab
GROUP_FUNC> indexJunctions
GROUP_ARGS> {'mode': 'gene', 'fields': None, 'action': 'set'}
CLONE_FUNC> distanceClones
CLONE_ARGS> {'seq_field': 'JUNCTION', 'sym': 'avg', 'model': 'hh_s5f', 'linkage': 'single', 'distance': 0.2, 'norm': 'len'}
     NPROC> 4

PROGRESS> Grouping sequences
PROGRESS> 12:53:18 (2) 0.0 min

PROGRESS> Assigning clones
PROGRESS> 12:53:18 [####################] 100% (2) 0.0 min

 OUTPUT> changeo_input_H_clone-pass.tab
 CLONES> 1
RECORDS> 2
   PASS> 2
   FAIL> 0
    END> DefineClones

     START> DefineClones
   DB_FILE> changeo_input_L.tab
GROUP_FUNC> indexJunctions
GROUP_ARGS> {'mode': 'gene', 'fields': None, 'action': 'set'}
CLONE_FUNC> distanceClones
CLONE_ARGS> {'sym': 'avg', 'linkage': 'single', 'distance': 0.2, 'norm': 'len', 'seq_field': 'JUNCTION', 'model': 'hh_s5f'}
     NPROC> 4

PROGRESS> Grouping sequences
PROGRESS> 12:53:19 (3) 0.0 min

PROGRESS> Assigning clones
PROGRESS> 12:53:19 [####################] 100% (3) 0.0 min

 OUTPUT> changeo_input_L_clone-pass.tab
 CLONES> 2
RECORDS> 3
   PASS> 3
   FAIL> 0
    END> DefineClones

Traceback (most recent call last):
  File "/usr/local/bin/bracer", line 11, in <module>
    load_entry_point('bracer==0.1', 'console_scripts', 'bracer')()
  File "/usr/local/lib/python3.5/dist-packages/bracer-0.1-py3.5.egg/bracerlib/launcher.py", line 43, in launch
    Task().run()
  File "/usr/local/lib/python3.5/dist-packages/bracer-0.1-py3.5.egg/bracerlib/tasks.py", line 863, in run
    self.plot_length_distributions(self.loci, length_filename_root, cells)
  File "/usr/local/lib/python3.5/dist-packages/bracer-0.1-py3.5.egg/bracerlib/tasks.py", line 1186, in plot_length_distributions
    sns.distplot(lns)
  File "/usr/local/lib/python3.5/dist-packages/seaborn/distributions.py", line 224, in distplot
    kdeplot(a, vertical=vertical, ax=ax, color=kde_color, **kde_kws)
  File "/usr/local/lib/python3.5/dist-packages/seaborn/distributions.py", line 657, in kdeplot
    cumulative=cumulative, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/seaborn/distributions.py", line 284, in _univariate_kdeplot
    x, y = _scipy_univariate_kde(data, bw, gridsize, cut, clip)
  File "/usr/local/lib/python3.5/dist-packages/seaborn/distributions.py", line 356, in _scipy_univariate_kde
    kde = stats.gaussian_kde(data, bw_method=bw)
  File "/usr/local/lib/python3.5/dist-packages/scipy/stats/kde.py", line 172, in __init__
    self.set_bandwidth(bw_method=bw_method)
  File "/usr/local/lib/python3.5/dist-packages/scipy/stats/kde.py", line 499, in set_bandwidth
    self._compute_covariance()
  File "/usr/local/lib/python3.5/dist-packages/scipy/stats/kde.py", line 510, in _compute_covariance
    self._data_inv_cov = linalg.inv(self._data_covariance)
  File "/usr/local/lib/python3.5/dist-packages/scipy/linalg/basic.py", line 819, in inv
    raise LinAlgError("singular matrix")
numpy.linalg.linalg.LinAlgError: singular matrix

Thanks for your help!
Uta

**Comment by UtaHar** [comment]
Hi again,

for your information, when testing the pipeline on a server and allocating more CPUs, the summarise function did work. I hope this helps,

Uta
