### ISSUE TITLE
Unrecognized error on  MakeDB (MakeDb.py: error: unrecognized arguments: --regions --scores)

### ISSUE THREAD

**Issue by tiagobrc** [Teichlab/bracer#41]
Hi,

I am trying to run bracer but I am getting this MakeDB error that I can't figure out the reason.
My MakeDb seems to be updated.
Can you please help me with this?

Thanks
MakeDb.py: 0.4.6 2019.07.19

```
Warning: [blastn] Examining 5 or more matches is recommended                                                                                  [25/5480]
##BCR_K##
Warning: [blastn] Examining 5 or more matches is recommended
##BCR_L##
Warning: [blastn] Examining 5 or more matches is recommended

##Running IgBLAST##
Ig_seqtype: Ig
Performing IgBlast on ['BCR_H', 'BCR_K', 'BCR_L']
##BCR_H##
##BCR_K##
##BCR_L##

usage: MakeDb.py [--version] [-h]  ...
MakeDb.py: error: unrecognized arguments: --regions --scores
Traceback (most recent call last):
  File "/ru-auth/local/home/trezende/bin/bracer", line 21, in <module>
    launch()
  File "/data_alpha/home/trezende/localPrograms/bracer/bracerlib/launcher.py", line 43, in launch
    Task().run()
  File "/data_alpha/home/trezende/localPrograms/bracer/bracerlib/tasks.py", line 374, in run
    cell = self.ig_blast() # Run IgBlast
  File "/data_alpha/home/trezende/localPrograms/bracer/bracerlib/tasks.py", line 547, in ig_blast
    self.create_changeo_db()
  File "/data_alpha/home/trezende/localPrograms/bracer/bracerlib/tasks.py", line 581, in create_changeo_db
    ungapped_seq_location, self.cell_name)
  File "/data_alpha/home/trezende/localPrograms/bracer/bracerlib/bracer_func.py", line 2230, in run_MakeDb_for_cell
    subprocess.check_call(command)
  File "/ru-auth/local/home/trezende/anaconda3/envs/bioconda3/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['MakeDb.py', 'igblast', '-i', '/gamma_data1/trezende/Juhee/Plate5_A12/Plate5_A12/IgBLAST_output/Plate5_A12_BCR_H.fmt7', '-s', '/gamma_data1/trezende/Juhee/Plate5_A12/Plate5_A12/Trinity_output/Plate5_A12_BCR_H.Trinity.fasta', '-r', '/data_alpha/home/trezende/localPrograms/bracer/resources/Mmus/imgt_gapped_resources/raw_seqs/BCR_H_V.fa', '/data_alpha/home/trezende/localPrograms/bracer/resources/Mmus/raw_seqs/BCR_H_D.fa', '/data_alpha/home/trezende/localPrograms/bracer/resources/Mmus/raw_seqs/BCR_H_J.fa', '--regions', '--scores']' returned non-zero exit status 2.


```

**Comment by mstubb** [comment]
It looks like ChangeO has changed its command line arguments to remove the `--regions` and `--scores` options in the latest releases (https://changeo.readthedocs.io/en/0.4.6/news.html). 

For now, try using version 0.4.5 of ChangeO.

Thanks,

Mike

**Comment by tiagobrc** [comment]
Thanks, that solves the issue.
