### ISSUE TITLE
Error during bracer summarize 

### ISSUE THREAD

**Issue by tiagobrc** [Teichlab/bracer#42]
During summarization, an error is shown. It does not have a lot of information so I can't figure it out.

Do any of you have an idea of what I could possibly be doing wrong?

EDITED: Now no error message is shown but summarized files are empty, no BCR reconstruction is shown.

```

Traceback (most recent call last):
  File "/ru-auth/local/home/trezende/anaconda3/envs/py37/bin/bracer", line 11, in <module>
    load_entry_point('bracer==0.1', 'console_scripts', 'bracer')()
  File "/ru-auth/local/home/trezende/anaconda3/envs/py37/lib/python3.7/site-packages/bracer-0.1-py3.7.egg/bracerlib/launcher.py", line 43, in launch
    Task().run()
  File "/ru-auth/local/home/trezende/anaconda3/envs/py37/lib/python3.7/site-packages/bracer-0.1-py3.7.egg/bracerlib/tasks.py", line 736, in run
    subdirectories = next(os.walk(self.root_dir))[1]
StopIteration

```

**Comment by mstubb** [comment]
Hi,

Please can you let us know the command that you ran that led to you getting this error?

Thanks,

Mike

**Comment by idalind** [comment]
Hello, apologies for not seeing this post before today. Did you successfully run bracer assemble for all the cells prior to running summarise? It seems to me like you are not providing the correct path to the directory containing all the assembled cells you would like to summarise. Could this be the case?

**Comment by tiagobrc** [comment]
I fixed the problem by just reinstalling anaconda and all requirements. Thanks!
