### ISSUE TITLE
Running igblast --regions --scores options are not recognizes

### ISSUE THREAD

**Issue by tAndreani** [Teichlab/bracer#47]
Hello,  

I have installed bracer in my local machine and I am trying the test 

`python bracer test -p 2 -c bracer.conf run`

to see if everything worked fine.  

After mapping and trinity assembly there is the step of blasting the assembled sequences. While running igblast, Bracer is running MakeDb.py, but it cannot recognize the options --regions --scores that I believe are included in bracer while running MakeDb.py. You can see the error below **MakeDb.py: error: unrecognized arguments: --regions --scores**:   

```
usage: MakeDb.py [--version] [-h]  ...
MakeDb.py: error: unrecognized arguments: --regions --scores
Traceback (most recent call last):
  File "bracer", line 21, in <module>
    launch()
  File "/site/ne/home/i0439277/bracer/bracer-master/bracerlib/launcher.py", line 43, in launch
    Task().run()
  File "/site/ne/home/i0439277/bracer/bracer-master/bracerlib/tasks.py", line 2008, in run
    trimmed_fastq2=self.trimmed_fastq2).run()
  File "/site/ne/home/i0439277/bracer/bracer-master/bracerlib/tasks.py", line 374, in run
    cell = self.ig_blast() # Run IgBlast
  File "/site/ne/home/i0439277/bracer/bracer-master/bracerlib/tasks.py", line 547, in ig_blast
    self.create_changeo_db()
  File "/site/ne/home/i0439277/bracer/bracer-master/bracerlib/tasks.py", line 581, in create_changeo_db
    ungapped_seq_location, self.cell_name)
  File "/site/ne/home/i0439277/bracer/bracer-master/bracerlib/bracer_func.py", line 2234, in run_MakeDb_for_cell
    subprocess.check_call(command)
  File "/site/ne/home/i0439277/anaconda3/envs/bracer_env/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['MakeDb.py', 'igblast', '-i', '/site/ne/home/i0439277/bracer/bracer-master/test_data/results/cell1/IgBLAST_output/cell1_BCR_K.fmt7', '-s', '/site/ne/home/i0439277/bracer/bracer-master/test_data/results/cell1/Trinity_output/cell1_BCR_K.Trinity.fasta', '-r', '/site/ne/home/i0439277/bracer/bracer-master/resources/Hsap/imgt_gapped_resources/raw_seqs/BCR_K_V.fa', '/site/ne/home/i0439277/bracer/bracer-master/resources/Hsap/raw_seqs/BCR_H_D.fa', '/site/ne/home/i0439277/bracer/bracer-master/resources/Hsap/raw_seqs/BCR_K_J.fa', '--regions', '--scores']' returned non-zero exit status 2.
```

If I run the same command removing `--regions --scores ` it works: 
```
 MakeDb.py igblast -i /site/ne/home/i0439277/bracer/bracer-master/test_data/results/cell1/IgBLAST_output/cell1_BCR_K.fmt7 -s /site/ne/home/i0439277/bracer/bracer-master/test_data/results/cell1/Trinity_output/cell1_BCR_K.Trinity.fasta -r /site/ne/home/i0439277/bracer/bracer-master/resources/Hsap/imgt_gapped_resources/raw_seqs/BCR_K_V.fa /site/ne/home/i0439277/bracer/bracer-master/resources/Hsap/raw_seqs/BCR_H_D.fa /site/ne/home/i0439277/bracer/bracer-master/resources/Hsap/raw_seqs/BCR_K_J.fa
       START> MakeDB
     ALIGNER> IgBLAST
ALIGNER_FILE> cell1_BCR_K.fmt7
    SEQ_FILE> cell1_BCR_K.Trinity.fasta
     ASIS_ID> False
  ASIS_CALLS> False
     PARTIAL> False
    EXTENDED> False

PROGRESS> 09:34:38 |Done                | 0.0 min

PROGRESS> 09:34:38 |####################| 100% (1) 0.0 min

OUTPUT> cell1_BCR_K_db-pass.tab
  PASS> 1
  FAIL> 0
   END> MakeDb
```

Has anyone encountered the same issue? How can avoid it? Thank you for any feedback. I am open to modify that part in the software.

**Comment by tAndreani** [comment]
Solved downloading the version `changeo-0.4.4.tar.gz` for now...
