### ISSUE TITLE
bracer summarise returns ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by tAndreani** [Teichlab/bracer#57]
Hello,  

i am trying to run `bracer summarize` with the ouput of `bracer assemble` (something i did several times for other projects). Within the folder `filtered_BCR_seqs` there are the BCR sequences and these are present for all my samples.  

However when i try to infer the clonotype network running:

`bracer summarise --config_file bracer.conf --use_unfiltered  --graph_format jpeg --infer_lineage processed_files/`  

I have this error:

```
Traceback (most recent call last):
  File "/site/ne/app/x86_64/bracer/bracer", line 21, in <module>
    launch()
  File "/site/ne/app/x86_64/bracer/bracerlib/launcher.py", line 43, in launch
    Task().run()
  File "/site/ne/app/x86_64/bracer/bracerlib/tasks.py", line 771, in run
    self.loci, cells)
  File "/site/ne/app/x86_64/bracer/bracerlib/tasks.py", line 1066, in write_reconstruction_statistics
    pc = round((count/float(total_cells))*100, 1)
ZeroDivisionError: float division by zero
```

what could be the error? It seems someting related to the statistic, but my fasta files with the BCRs assembled within the `filtered_BCR_seqs` folders are not empy, they all have heavy or/and light chains..

Any idea?
Thanks!

**Comment by tAndreani** [comment]
it was a folder location issue. I run bracer in a different location respect of where was installed and this command did not work.
