### ISSUE TITLE
Installation help. Get ~/.bracerrc set up and AssertionError on test. 

### ISSUE THREAD

**Issue by jolespin** [Teichlab/bracer#63]
Here's my conda environment: 
```
(bracer_env) -bash-4.2$ conda list
# packages in environment at /usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/bracer_env:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
_r-mutex                  1.0.1               anacondar_1    conda-forge
airr                      1.3.1                    pypi_0    pypi
atk-1.0                   2.36.0               h3371d22_4    conda-forge
binutils_impl_linux-64    2.36.1               h193b22a_2    conda-forge
binutils_linux-64         2.36                 hf3e587d_2    conda-forge
biopython                 1.79                     pypi_0    pypi
blas                      1.1                    openblas    conda-forge
blast                     2.12.0          pl5262h3289130_0    bioconda
bowtie2                   2.3.5.1          py36he513fc3_0    bioconda
bracer                    0.1                      pypi_0    pypi
bwidget                   1.9.14               ha770c72_1    conda-forge
bz2file                   0.98                       py_0    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
cairo                     1.16.0            ha00ac49_1009    conda-forge
changeo                   1.2.0                    pypi_0    pypi
collectl                  4.0.4                         2    bioconda
curl                      7.80.0               h2574ce0_0    conda-forge
cutadapt                  3.5                      pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
dataclasses               0.8                      pypi_0    pypi
decorator                 5.1.0                    pypi_0    pypi
dnaio                     0.6.0                    pypi_0    pypi
entrez-direct             16.2                 he881be0_0    bioconda
expat                     2.4.2                h9c3ff4c_0    conda-forge
fastool                   0.1.4                h5bf99c6_5    bioconda
fastqc                    0.11.9               hdfd78af_1    bioconda
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.13.1            hba837de_1005    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
fribidi                   1.0.10               h36c2ea0_0    conda-forge
future                    0.18.2                   pypi_0    pypi
gcc_impl_linux-64         9.4.0               h03d3576_11    conda-forge
gcc_linux-64              9.4.0                h391b98a_2    conda-forge
gdk-pixbuf                2.42.6               h04a7f16_0    conda-forge
gettext                   0.19.8.1          h73d1719_1008    conda-forge
gfortran_impl_linux-64    9.4.0               h0003116_11    conda-forge
gfortran_linux-64         9.4.0                hf0ab688_2    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
graphite2                 1.3.13            h58526e2_1001    conda-forge
graphviz                  2.50.0               h85b4f2f_1    conda-forge
gsl                       2.7                  he838d99_0    conda-forge
gtk2                      2.24.33              h539f30e_1    conda-forge
gts                       0.7.6                h64030ff_2    conda-forge
gxx_impl_linux-64         9.4.0               h03d3576_11    conda-forge
gxx_linux-64              9.4.0                h0316aca_2    conda-forge
harfbuzz                  3.2.0                hb4a5f5f_0    conda-forge
hdf5                      1.10.6          nompi_h6a2412b_1114    conda-forge
htslib                    1.9                  h4da6232_3    bioconda
icu                       69.1                 h9c3ff4c_0    conda-forge
igblast                   1.17.1               h388d1fa_0    bioconda
importlib-metadata        4.8.3                    pypi_0    pypi
isal                      0.11.1                   pypi_0    pypi
java-jdk                  7.0.91                        1    bioconda
jbig                      2.1               h7f98852_2003    conda-forge
jellyfish                 2.2.10               h6bb024c_1    bioconda
jemalloc                  4.5.0                         0    bioconda
jpeg                      9d                   h36c2ea0_0    conda-forge
kallisto                  0.46.2               h60f4f9f_2    bioconda
kernel-headers_linux-64   2.6.32              he073ed8_15    conda-forge
kiwisolver                1.3.1                    pypi_0    pypi
krb5                      1.19.2               hcc1bbae_3    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      3.0                  h9c3ff4c_0    conda-forge
libblas                   3.9.0           1_h86c2bf4_netlib    conda-forge
libcblas                  3.9.0           5_h92ddd45_netlib    conda-forge
libcurl                   7.80.0               h2574ce0_0    conda-forge
libdeflate                1.8                  h7f98852_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-devel_linux-64     9.4.0               hd854feb_11    conda-forge
libgcc-ng                 11.2.0              h1d223b6_11    conda-forge
libgd                     2.3.3                h3cfcdeb_1    conda-forge
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            11.2.0              h69a702a_11    conda-forge
libgfortran5              11.2.0              h5c6108e_11    conda-forge
libglib                   2.70.2               h174f98d_0    conda-forge
libgomp                   11.2.0              h1d223b6_11    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0           5_h92ddd45_netlib    conda-forge
libnghttp2                1.43.0               h812cca2_1    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
librsvg                   2.52.5               hc3c00ef_0    conda-forge
libsanitizer              9.4.0               h79bfe98_11    conda-forge
libssh2                   1.10.0               ha56f1ee_2    conda-forge
libstdcxx-devel_linux-64  9.4.0               hd854feb_11    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_11    conda-forge
libtiff                   4.3.0                h6f004c6_2    conda-forge
libtool                   2.4.6             h9c3ff4c_1008    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp                   1.2.1                h3452ae3_0    conda-forge
libwebp-base              1.2.1                h7f98852_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxml2                   2.9.12               h885dcf4_1    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
make                      4.3                  hd18ef5c_1    conda-forge
matplotlib                3.3.4                    pypi_0    pypi
mmtf-python               1.1.2                      py_0    conda-forge
mock                      4.0.3                    pypi_0    pypi
msgpack-python            1.0.2            py36hff7bd54_1
ncbi-vdb                  2.11.0               h1b792b2_1    bioconda
ncurses                   6.2                  h58526e2_4    conda-forge
networkx                  1.11                     pypi_0    pypi
numpy                     1.19.5                   pypi_0    pypi
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openblas                  0.2.19                        2    conda-forge
openjdk                   10.0.2            h14c3975_1015    conda-forge
openssl                   1.1.1l               h7f98852_0    conda-forge
pandas                    0.24.2           py36hf484d3e_0    conda-forge
pango                     1.48.10              h54213e6_2    conda-forge
parafly                   r2013_01_21                   1    bioconda
patsy                     0.5.2              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pcre2                     10.37                h032f7d1_0    conda-forge
perl                      5.26.2            h36c2ea0_1008    conda-forge
perl-archive-tar          2.32                    pl526_0    bioconda
perl-carp                 1.38                    pl526_3    bioconda
perl-common-sense         3.74                    pl526_2    bioconda
perl-compress-raw-bzip2   2.087           pl526he1b5a44_0    bioconda
perl-compress-raw-zlib    2.087           pl526hc9558a2_0    bioconda
perl-exporter             5.72                    pl526_1    bioconda
perl-exporter-tiny        1.002001                pl526_0    bioconda
perl-extutils-makemaker   7.36                    pl526_1    bioconda
perl-io-compress          2.087           pl526he1b5a44_0    bioconda
perl-io-zlib              1.10                    pl526_2    bioconda
perl-json                 4.02                    pl526_0    bioconda
perl-json-xs              2.34            pl526h6bb024c_3    bioconda
perl-list-moreutils       0.428                   pl526_1    bioconda
perl-list-moreutils-xs    0.428                   pl526_0    bioconda
perl-pathtools            3.75            pl526h14c3975_1    bioconda
perl-scalar-list-utils    1.52            pl526h516909a_0    bioconda
perl-threaded             5.26.0                        0    bioconda
perl-types-serialiser     1.0                     pl526_2    bioconda
perl-xsloader             0.24                    pl526_0    bioconda
phylip                    3.697                h470a237_0    bioconda
pigz                      2.6                  h27826a3_0    conda-forge
pillow                    8.4.0                    pypi_0    pypi
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
presto                    0.7.0                    pypi_0    pypi
prettytable               2.5.0                    pypi_0    pypi
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pydotplus                 2.0.2                    pypi_0    pypi
pyparsing                 3.0.6                    pypi_0    pypi
python                    3.6.15          hb7a2778_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-levenshtein        0.12.2                   pypi_0    pypi
python_abi                3.6                     2_cp36m    conda-forge
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0                      pypi_0    pypi
r-ape                     5.5               r41h306847c_0    conda-forge
r-base                    4.1.2                hde4fec0_0    conda-forge
r-lattice                 0.20_45           r41hcfec24a_0    conda-forge
r-nlme                    3.1_153           r41h859d828_0    conda-forge
r-rcpp                    1.0.7             r41h03ef668_0    conda-forge
r-rphylip                 0.1_23          r41ha770c72_1003    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
reportlab                 3.5.68           py36h3e18861_0    conda-forge
samtools                  1.7                           1    bioconda
scipy                     1.5.4                    pypi_0    pypi
seaborn                   0.11.2                   pypi_0    pypi
sed                       4.8                  he412f7d_0    conda-forge
setuptools                58.0.4           py36h5fab9bb_2    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
slclust                   02022010                      2    bioconda
sqlite                    3.37.0               h9cd32fc_0    conda-forge
statsmodels               0.8.0                    py36_0    conda-forge
sysroot_linux-64          2.12                he073ed8_15    conda-forge
tbb                       2021.4.0             h4bd325d_1    conda-forge
tk                        8.6.11               h27826a3_1    conda-forge
tktable                   2.10                 hb7b940f_3    conda-forge
trim-galore               0.6.7                hdfd78af_0    bioconda
trimmomatic               0.39                 hdfd78af_2    bioconda
trinity                   2.1.1                         6    bioconda
typing-extensions         4.0.1                    pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
xopen                     1.2.1                    pypi_0    pypi
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-libxt                1.2.1                h7f98852_2    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yamlordereddictloader     0.4.0                    pypi_0    pypi
zipp                      3.6.0                    pypi_0    pypi
zlib                      1.2.11            h36c2ea0_1013    conda-forge
zstd                      1.5.0                ha95c52a_0    conda-forge
```

Here's my install directory: 

```
(bracer_env) -bash-4.2$ ls
bracer.conf  bracer.egg-info  bracerlib  build  Dockerfile  docker_helper_files  LICENSE  lineage.R  README.md  requirements.txt  resources  setup.py  test_data
```

Here's what happens when I run test: 
```
(bracer_env) -bash-4.2$ bracer test -p 4 -c bracer.conf
Please specify the path to where you originally installed BraCeR in the config file.
Please specify the path to where you originally installed BraCeR in the config file.
Traceback (most recent call last):
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/bracer_env/bin/bracer", line 8, in <module>
    sys.exit(launch())
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/bracer_env/lib/python3.6/site-packages/bracerlib/launcher.py", line 43, in launch
    Task().run()
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/bracer_env/lib/python3.6/site-packages/bracerlib/tasks.py", line 2008, in run
    trimmed_fastq2=self.trimmed_fastq2).run()
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/bracer_env/lib/python3.6/site-packages/bracerlib/tasks.py", line 298, in __init__
    root=resource_dir)
  File "/usr/local/devel/ANNOTATION/jespinoz/anaconda3/envs/bracer_env/lib/python3.6/site-packages/bracerlib/tasks.py", line 184, in get_species_root
    assert os.path.isdir(resources_root), "Species not found in resources"
AssertionError: Species not found in resources
```

My current ~/.bracerrc file: 

```
(bracer_env) -bash-4.2$ cat ~/.bracerrc
bracer_path=/usr/local/devel/ANNOTATION/jespinoz/Packages/bracer
```

# What I need help with: 
1. How do I set up my ~/.bracerrc file so it knows where the config is located? 
2. How can I get the test to run?

**Comment by NickEngland** [comment]
Hi @jolespin by running "bracer test -c bracer.conf" bracer will use the bracer.conf file specified rather than your ~/.bracerrc which it uses if you don't specify any config file. You should edit your bracer.conf to have the correct bracer_path and re-run. Or copy all the settings into your ~/.bracerrc and run without the "-c bracer.conf"
