### ISSUE TITLE
Docker images not working

### ISSUE THREAD

**Issue by wyattmcdonnell** [Teichlab/bracer#8]
Hi Mike et al. very excited to use BraCeR--attempted to run Docker images on 16/11/2017, ran following commands to install: 
```
docker pull teichlab/bracer
```
Installation proceeded without issue. 
Docker version for Windows:
```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: true
```
Docker version for Mac OS X (OS X 10.11.6, El Capitan):
```
Client: 
 Version: 17.09.0-ce
 API version: 1.32
 Go version: go1.8.3
 Git commit: afdb6d4
 Built: Tue Sep 26 22:40:09 2017
 OS/Arch: darwin/amd64

Server:
 Version 17.09.0-ce
 API version: 1.32 (minimum version 1.12)
 Go version: go1.8.3
 Git commit: afdb6d4
 Built: Tue Sep 26 22:45:38 2017
 OS/Arch: linux/amd64
 Experimental: true
```

On Mac OS X after running this: 
```
docker run teichlab/bracer test
```
... the following break appears: 
```
Traceback (most recent call last):
  File "/usr/local/bin/bracer", line 11, in <module>
    load_entry_point('bracer==0.1', 'console_scripts', 'bracer')()
  File "/usr/local/lib/python3.5/dist-packages/bracer-0.1-py3.5.egg/bracerlib/launcher.py", line 43, in launch
    Task().run()
  File "/usr/local/lib/python3.5/dist-packages/bracer-0.1-py3.5.egg/bracerlib/tasks.py", line 1937, in run
    trimmed_fastq2=self.trimmed_fastq2).run()
  File "/usr/local/lib/python3.5/dist-packages/bracer-0.1-py3.5.egg/bracerlib/tasks.py", line 369, in run
    self.quantify(cell)
  File "/usr/local/lib/python3.5/dist-packages/bracer-0.1-py3.5.egg/bracerlib/tasks.py", line 605, in quantify
    self.trimmed_fastq2, self.keep_trimmed_reads)
  File "/usr/local/lib/python3.5/dist-packages/bracer-0.1-py3.5.egg/bracerlib/bracer_func.py", line 2110, in quantify_with_kallisto
    subprocess.check_call(index_command)
  File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/kallisto_linux-v0.43.1/kallisto', 'index', '-i', '/bracer/test_data/results/cell1/expression_quantification/kallisto_index/cell1_transcriptome.idx', '/bracer/test_data/results/cell1/expression_quantification/kallisto_index/cell1_transcriptome.fa']' returned non-zero exit status -9
```
On Windows 10 after running the same command: 
```
docker run teichlab/bracer test
```
... the following break appears: 
```
Traceback (most recent call last):
  File "/usr/local/bin/bracer", line 11, in <module>
    load_entry_point('bracer==0.1', 'console_scripts', 'bracer')()
  File "/usr/local/lib/python3.5/dist-packages/bracer-0.1-py3.5.egg/bracerlib/launcher.py", line 43, in launch
    Task().run()
  File "/usr/local/lib/python3.5/dist-packages/bracer-0.1-py3.5.egg/bracerlib/tasks.py", line 1937, in run
    trimmed_fastq2=self.trimmed_fastq2).run()
  File "/usr/local/lib/python3.5/dist-packages/bracer-0.1-py3.5.egg/bracerlib/tasks.py", line 369, in run
    self.quantify(cell)
  File "/usr/local/lib/python3.5/dist-packages/bracer-0.1-py3.5.egg/bracerlib/tasks.py", line 605, in quantify
    self.trimmed_fastq2, self.keep_trimmed_reads)
  File "/usr/local/lib/python3.5/dist-packages/bracer-0.1-py3.5.egg/bracerlib/bracer_func.py", line 2110, in quantify_wi
th_kallisto
    subprocess.check_call(index_command)
  File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/kallisto_linux-v0.43.1/kallisto', 'index', '-i', '/bracer/test_data/results/c
ell1/expression_quantification/kallisto_index/cell1_transcriptome.idx', '/bracer/test_data/results/cell1/expression_quan
tification/kallisto_index/cell1_transcriptome.fa']' returned non-zero exit status -9
```

**Comment by wyattmcdonnell** [comment]
Other issue that's popping up after navigating to appropriate FASTQ-containing folder...

After navigating to appropriate folder on Windows and Mac OS X: 
```
cd .\seqdata\
```

... and running the following: 
```
docker run teichlab/bracer assemble output output2 .\test1.FASTQ .\test2.FASTQ
```
this break appears: 
```
Traceback (most recent call last):
  File "/usr/local/bin/bracer", line 11, in <module>
    load_entry_point('bracer==0.1', 'console_scripts', 'bracer')()
  File "/usr/local/lib/python3.5/dist-packages/bracer-0.1-py3.5.egg/bracerlib/launcher.py", line 43, in launch
    Task().run()
  File "/usr/local/lib/python3.5/dist-packages/bracer-0.1-py3.5.egg/bracerlib/tasks.py", line 312, in __init__
    raise OSError('2', 'FASTQ file not found', self.fastq1)
OSError: [Errno 2] FASTQ file not found: '.\\test1.FASTQ'
```
Same issue pops up when running this: 
```
docker run teichlab/bracer assemble output output2 test1.FASTQ test2.FASTQ
```

...same error appears: 
```
Traceback (most recent call last):
  File "/usr/local/bin/bracer", line 11, in <module>
    load_entry_point('bracer==0.1', 'console_scripts', 'bracer')()
  File "/usr/local/lib/python3.5/dist-packages/bracer-0.1-py3.5.egg/bracerlib/launcher.py", line 43, in launch
    Task().run()
  File "/usr/local/lib/python3.5/dist-packages/bracer-0.1-py3.5.egg/bracerlib/tasks.py", line 312, in __init__
    raise OSError('2', 'FASTQ file not found', self.fastq1)
OSError: [Errno 2] FASTQ file not found: 'test1.FASTQ'
```

**Comment by ktpolanski** [comment]
As stated in the readme, running the Docker image requires setting up a volume so that BraCeR can actually see the files you give it and you can actually see the output it produces. Try replacing `docker run teichlab/bracer` with `docker run -it --rm -v $PWD:/scratch -w /scratch teichlab/bracer`, as specified in the readme. Should hopefully work.

And as to the test failing, this might be the memory issue you bumped into earlier, Mike?

**Comment by wyattmcdonnell** [comment]
@ktpolanski thanks so much for your help. Going to close this issue as Mike already addressed that the memory needs to be upped--was able to run with 8 GB allocated to Docker on Windows and Mac OS X if you feel that would be helpful to add to documentation. Have a great day!
